### ISSUE TITLE
High Availability mode ?

### ISSUE THREAD

**Issue by wonhee0410** [bitfront-se/bytesafe-ce#1]
Dear All,

I really appreciated your community version of ByteSafe product.

A question is does this community version support High Availability mode or something like this ?

Thank you very much.

**Comment by niclas-g** [comment]
Bytesafe-CE does not have any HA capabilities built in. 
There are some limitations that prevents you from running multiple Bytesafe CE instances that manages the same workspace, so any high availability setup for Bytesafe CE would need to be deployed in an active/standby configuration.

We do provide some sample deployments (docker compose, k8s, etc.) but we have not provided any setup that is resilient for infrastructure failures.
However, there is nothing that prevents you or anyone from deploying Bytesafe Community Edition in a high availability environment and we would encourage anyone to open a PR for such a config/sample under examples/.

**Comment by wonhee0410** [comment]
> Bytesafe-CE does not have any HA capabilities built in. There are some limitations that prevents you from running multiple Bytesafe CE instances that manages the same workspace, so any high availability setup for Bytesafe CE would need to be deployed in an active/standby configuration.
> 
> We do provide some sample deployments (docker compose, k8s, etc.) but we have not provided any setup that is resilient for infrastructure failures. However, there is nothing that prevents you or anyone from deploying Bytesafe Community Edition in a high availability environment and we would encourage anyone to open a PR for such a config/sample under examples/.

Thank you very much !
