### ISSUE TITLE
Change email address of user

### ISSUE THREAD

**Issue by wonhee0410** [bitfront-se/bytesafe-ce#11]
Hi all,

How can I change the email address of user on Bytesafe ?

Thank you.

![image](https://github.com/bitfront-se/bytesafe-ce/assets/60768442/94009af2-2a93-4bec-a9a6-d78e25f81108)

**Comment by dp-coder** [comment]
Hi @wonhee0410!

All users are stored in the database table **login_password**. To update an email address you’ll need to update the **email** field for the user.

Hope that helps.

Best, Daniel

**Comment by wonhee0410** [comment]
> Hi @wonhee0410!
> 
> All users are stored in the database table **login_password**. To update an email address you’ll need to update the **email** field for the user.
> 
> Hope that helps.
> 
> Best, Daniel

Thank you.

So if I want to reset user password directly from database, how can I do that ?

**Comment by dp-coder** [comment]
You're welcome. Changing passwords will have to be done using

`https://<domain>/change-password`

as passwords are encrypted in the database.
