### ISSUE TITLE
LDAP Integration

### ISSUE THREAD

**Issue by wonhee0410** [bitfront-se/bytesafe-ce#12]
Hi all,

I would like to authenticate with LDAP, how can I setup this on Bytesafe.

Thank you.

**Comment by dp-coder** [comment]
Hi,

Unfortunately, LDAP integration is not supported, as Bytesafe Community Edition only supports user/password login.

Our commercial Bytesafe plans support Social Logins and SAML-integration for SSO. For more information:

- https://docs.bytesafe.dev/account-and-profile/single-sign-on-sso-using-social-login/
- https://docs.bytesafe.dev/account-and-profile/single-sign-on-sso-using-saml/

Kind regards, Daniel
