### ISSUE TITLE
Access token expired before the date

### ISSUE THREAD

**Issue by wonhee0410** [bitfront-se/bytesafe-ce#13]
Hello all,

When using Bytesafe for building maven application, after 1-2 months, it will generate the error 401 - Unauthorized.

When I regenerate the token, the error disappear and it takes time to do this.

Are there any solutions for this problem.

Thank you.

**Comment by wallrat** [comment]
It sounds like you are using your browser token to access maven. Are you following this https://docs.bytesafe.dev/getting-started/managing-tokens/#generate-new-token to create the token?

Access tokens are by default valid for 10 years.

**Comment by wonhee0410** [comment]
> It sounds like you are using your browser token to access maven. Are you following this https://docs.bytesafe.dev/getting-started/managing-tokens/#generate-new-token to create the token?
> 
> Access tokens are by default valid for 10 years.

I used the Generate token button to create the Access Token.
