### ISSUE TITLE
Download JAR via API

### ISSUE THREAD

**Issue by JensWinkler91** [bitfront-se/bytesafe-ce#15]
I'm using bytesafe as a maven repository. I deploy a jar file to my bytesafe instance what is used in a NodeJs project.
Whenever the jar files changes, i need to login into bytesafe and download it manually.

Is there any way to download the jar file using a rest api?

**Comment by wallrat** [comment]
Yes, you only need to provide authentication token.

Maven uses the following path structure to download files from a registry:

`https://{repository}/{groupId path with slashes}/{artifactId}/{version}/{filename}`

ex Maven Central `https://repo1.maven.org/maven2/org/apache/commons/commons-release-plugin/1.8.2/commons-release-plugin-1.8.2.jar`

the same example for Bytesafe would be (registry called 'my-repo'):

`https://bytesafe.example.com/maven/my-repo/org/apache/commons/commons-release-plugin/1.8.2/commons-release-plugin-1.8.2.jar`

download with curl:

`curl -H 'Authorization: Bearer XXXXXXXXXXX' -L -O 'https://bytesafe.example.com/maven/my-repo/org/apache/commons/commons-release-plugin/1.8.2/commons-release-plugin-1.8.2.jar'`

You can of course also use the same url you see when you download from the workspace UI (i.e. /blob/xxxxx) if you know the hash of the file (and provide a auth token as above).

**Comment by JensWinkler91** [comment]
Thank you for your support! It worked!
