### ISSUE TITLE
Get latest version of JAR via API

### ISSUE THREAD

**Issue by JensWinkler91** [bitfront-se/bytesafe-ce#16]
I'm using bytesafe as a maven repository. I deploy a jar file to my bytesafe instance what is used in a NodeJs project.
Whenever the jar files changes, i need to download the latest version.

Is there any way to download the latest jar or to get the latest version? I would also help if there's a possiblity to get all existing versions.

**Comment by wallrat** [comment]
> Is there any way to download the latest jar or to get the latest version?

Yes. I suggest you use the same protocol as Maven does. Let's take a random example from Maven central:

The package `com.google.guava:guava@33.2.1-jre`

https://repo1.maven.org/maven2/com/google/guava/guava/maven-metadata.xml gives you the latest version.
https://repo1.maven.org/maven2/com/google/guava/guava/33.2.1-jre/guava-33.2.1-jre.jar is the latest jar.

In Bytesafe this would be something like

`curl -u bytesafe:{token} https://{bytesafe instance}/maven/{registry name}/com/google/guava/guava/maven-metadata.xml` 

Kind Regards,
Andreas

**Comment by JensWinkler91** [comment]
Hi Andreas,

thanks for your response.

I could get all versions (or also the last version) by fetching and parsing the `maven-metadata.xml`.

For anyone who's interested in it, here's a quick and dirty solution (`Kotlin`) that worked for me:

```
fun getVersions(token: String): List<String> {
        val url = URL("https://<yourdomain_to_bytesafe>/maven/<your_group_id>/maven-metadata.xml")
        val connection = url.openConnection() as HttpURLConnection

        try {
            // Set request method
            connection.requestMethod = "GET"

            // Add request headers
            connection.setRequestProperty("Authorization", "Bearer $token")

            // Get response code
            val responseCode = connection.responseCode

            // Read response
            val response = connection.inputStream.bufferedReader().use { it.readText() }

            val regex = Regex("<version>[0-9]+\\.[0-9]+\\.[0-9]+<\\/version>") // Regular expression to match words
            val versions =
                regex.findAll(response).map { it.value }.map { it.replace("<version>", "").replace("</version>", "") }
            return versions.toList().reversed().take(5)
        } catch (e: Exception) {
            e.printStackTrace()
        } finally {
            connection.disconnect()
        }

        return listOf()
    }
```

This code snippet will return the last 5 versions.

Beste Regards
Jens
