### ISSUE TITLE
Postgres SSL mode

### ISSUE THREAD

**Issue by conclusionlogic** [bitfront-se/bytesafe-ce#17]
Hello,

is there a way to set Postgres sslmode with Bytesafe?

I'd need to set `sslmode=require` to connect to an external Postgres DB and would prefer not to resort to using `stunnel` if possible.

Can I configure this via a Bytesafe command line parameter or some environment variable?

Thanks!

**Comment by wallrat** [comment]
Hi,

sorry for the delay. 

There is currently no config to set `sslmode`, but it's a very reasonable request and should be a quick fix. 

We can probably build a new CE release for that in a day or two.

Kind Regards,
Andreas

**Comment by wallrat** [comment]
We have released https://github.com/bitfront-se/bytesafe-ce/releases/tag/v1.0.12 that adds a DB_SSLMODE env var.

**Comment by conclusionlogic** [comment]
Cheers, this works!

**Comment by conclusionlogic** [comment]
Cheers, this works!
