### ISSUE TITLE
Something went wrong when creating user

### ISSUE THREAD

**Issue by GurdipS5** [bitfront-se/bytesafe-ce#18]
Hi,

I have setup bytesafe ce but when I try to sign in with an email address and password, I get this error:

"Something went wrong when creating user"

Could someone assist?

Thanks

**Comment by GurdipS5** [comment]
I found the error in the console tab from my browser:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8081/signup/auth/email. (Reason: CORS request did not succeed). Status code: (null).

How can I allow this? I am accessing the server via its private IP.

**Comment by niclas-g** [comment]
Hi, and thanks for using Bytesafe! 
Make sure that you use the same address when accessing Bytesafe as the one you specify with the URL_PREFIX option, check the docs for parameters here: 
https://docs.bytesafe.dev/community-edition/
