### ISSUE TITLE
Connection Reset by peer when pulling Maven package

### ISSUE THREAD

**Issue by wonhee0410** [bitfront-se/bytesafe-ce#4]
Dear All,

Thanks for your awesome project !

I'm using Bytesafe docker and running hehind a company proxy.

I have a problem when pulling package with Maven firewall, the error log bellow:

`bytesafe-bytesafe-ce-1  | time="2023-06-16T07:51:05Z" level=debug msg=FetchUpstreamMetadata artifactId=maven-clean-plugin groupId=org.apache.maven.plugins pkg=maven upstreamUrl="https://repo1.maven.org/maven2/"
bytesafe-bytesafe-ce-1  | time="2023-06-16T07:51:05Z" level=warning msg="maven.FetchUpstreamMetadata failed" error="Get \"https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-clean-plugin/maven-metadata.xml\": read tcp 172.20.0.4:51240->199.232.196.209:443: read: connection reset by peer" pkg=artifacts
bytesafe-bytesafe-ce-1  | time="2023-06-16T07:51:05Z" level=debug msg=ProbeForVersion action=ProbeForVersion artifactId=maven-clean-plugin groupId=org.apache.maven.plugins pkg=maven upstreamUrl="https://repo1.maven.org/maven2/" version=3.2.0
bytesafe-bytesafe-ce-1  | time="2023-06-16T07:51:05Z" level=debug msg="ProbeForVersion failed" action=fetchExternalUpstreamVersionsFromMaven error="Head \"https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-clean-plugin/3.2.0/maven-clean-plugin-3.2.0.pom\": read tcp 172.20.0.4:51242->199.232.196.209:443: read: connection reset by peer" package="org.apache.maven.plugins:maven-clean-plugin" pkg=artifacts requestId=01H31JZETNXWBB5ZT1VRJW3XVY upstream="Maven Central"
bytesafe-bytesafe-ce-1  | time="2023-06-16T07:51:05Z" level=debug msg="pullFromCandidates()" action=pullFromCandidates len(candidates)=0 pkg=artifacts
bytesafe-bytesafe-ce-1  | time="2023-06-16T07:51:05Z" level=warning msg="failed to pull missing .pom file" error="org.apache.maven.plugins:maven-clean-plugin@3.2.0 not found in registry or upstreams" file=maven-clean-plugin-3.2.0.jar packageName="org.apache.maven.plugins:maven-clean-plugin" packageVersion=3.2.0 pkg=artifacts pom=maven-clean-plugin-3.2.0.pom registry=01H31EXJG0MJ69ZQS8N81AMKV1
bytesafe-bytesafe-ce-1  | time="2023-06-16T07:51:05Z" level=debug msg=FetchUpstreamMetadata artifactId=maven-clean-plugin groupId=org.apache.maven.plugins pkg=maven upstreamUrl="https://repo1.maven.org/maven2/"
bytesafe-bytesafe-ce-1  | time="2023-06-16T07:51:05Z" level=warning msg="maven.FetchUpstreamMetadata failed" error="Get \"https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-clean-plugin/maven-metadata.xml\": read tcp 172.20.0.4:51248->199.232.196.209:443: read: connection reset by peer" pkg=artifacts
bytesafe-bytesafe-ce-1  | time="2023-06-16T07:51:05Z" level=debug msg=ProbeForVersion action=ProbeForVersion artifactId=maven-clean-plugin groupId=org.apache.maven.plugins pkg=maven upstreamUrl="https://repo1.maven.org/maven2/" version=3.2.0
bytesafe-bytesafe-ce-1  | time="2023-06-16T07:51:06Z" level=debug msg="ProbeForVersion failed" action=fetchExternalUpstreamVersionsFromMaven error="Head \"https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-clean-plugin/3.2.0/maven-clean-plugin-3.2.0.pom\": read tcp 172.20.0.4:51252->199.232.196.209:443: read: connection reset by peer" package="org.apache.maven.plugins:maven-clean-plugin" pkg=artifacts requestId=01H31JZETNXWBB5ZT1VRJW3XVY upstream="Maven Central"
bytesafe-bytesafe-ce-1  | time="2023-06-16T07:51:06Z" level=debug msg="pullFromCandidates()" action=pullFromCandidates len(candidates)=0 pkg=artifacts
bytesafe-bytesafe-ce-1  | time="2023-06-16T07:51:06Z" level=error msg="failed to pull package" accountId=bytesafe-ce action=get error="org.apache.maven.plugins:maven-clean-plugin@3.2.0 not found in registry or upstreams" packageName="org.apache.maven.plugins:maven-clean-plugin" path="{org.apache.maven.plugins maven-clean-plugin 3.2.0 maven-clean-plugin-3.2.0.jar jar}" pkg=maven registryName=test-fw`

I think that "Connection Reset by peer" means the traffic is not routed through proxy but I have configured with proxy environment variables and changed the config.json of docker.

Could you please help me with this problem ?

Thank you very much.

**Comment by niclas-g** [comment]
Thanks for reporting this issue!  We believe that we have resolved this issue in [v1.0.4](https://github.com/bitfront-se/bytesafe-ce/releases/tag/v1.0.4). Make sure to set the new parameter  ALLOW_PRIVATE_IPS=true   - We have included this in the [example docker compose config](https://raw.githubusercontent.com/bitfront-se/bytesafe-ce/main/docker-compose.yml)  

Please let us know if this solved your problem.

**Comment by wonhee0410** [comment]
> Thanks for reporting this issue! We believe that we have resolved this issue in [v1.0.4](https://github.com/bitfront-se/bytesafe-ce/releases/tag/v1.0.4). Make sure to set the new parameter ALLOW_PRIVATE_IPS=true - We have included this in the [example docker compose config](https://raw.githubusercontent.com/bitfront-se/bytesafe-ce/main/docker-compose.yml)
> 
> Please let us know if this solved your problem.

Thanks for your support.

It's working now !
