### ISSUE TITLE
Fail to connect to python with python firewall

### ISSUE THREAD

**Issue by tsukiazuma** [bitfront-se/bytesafe-ce#5]
I depoy repository for python and config upstream for it to https://pypi.org/simple/. Then add certificate of pypi.org to connect and it work very good.
But next day, it error failed to sign certificate and I must export to add again.
It happens every day, is there any way to fix it?

Thanks

**Comment by wallrat** [comment]
> Then add certificate of pypi.org to connect and it work very good. 

Can you give us a few more details of your setup? are you running the Docker image?

- **Why** do you need to 'add certificate of pypi.org'?
- **How** do you 'add certificate of pypi.org'? 

> But next day, it error failed to sign certificate and I must export to add again.

Can you attach the error to the issue?

Looking at the certificate for https://pypi.org/simple/, it's long lived and expires 30 May 2024, so at least the certificate isn't changing.

Bytesafe doesn't do anything special regarding CAs, it uses **/etc/ssl/certs/ca-certificates.crt** bundled in the image to validate certificates.

**Comment by tsukiazuma** [comment]
Yes, I deploy it with Docker

1. When I don't add certificate or add wrong certificate, I can't use feature upstream:
![image](https://github.com/bitfront-se/bytesafe-ce/assets/75791054/fbcaeccb-ddb2-4620-8344-d4caacee0c3e)
![image](https://github.com/bitfront-se/bytesafe-ce/assets/75791054/0ff54ad5-8f47-4ab6-bbf0-a6f03b46db04)

2. Step by step to add certificate of pypi.org
- Export certificate on pypi.org to file .cer
- Convert .cer to .crt and add to folder bytesafe on server
Then can use feature upstream

I do the same for the firewall maven repository, but it don't happen but it doesn't give an error like python

**Comment by wallrat** [comment]
The container should have no problem verifying certs, so my guess is that you are running behind a **proxy**?

If that is the case, are you accidentally adding a **short lived cert** issued by the proxy to the container, instead of the **CA** used by the proxy?

Please double check the type and expiry of the cert (e.g. `openssl x509 -in certificate.crt -text -noout`) you are adding to the container.

**Comment by tsukiazuma** [comment]
Yes, I am using proxy, but don't have certificate expired before 2024

**Comment by wallrat** [comment]
To summarize this thread so far:

- Bytesafe CE  is a standard Go application and uses the OS provided CAs to verify TLS connections. Nothing special whatsoever. 
- The container is very simple, based on SCRATCH with just our binary, CAs + timezone file.
- If you are using a proxy that intercepts HTTPS requests, you should mount your **proxy's CA certificate** in the container, not certificates for a specific sites.
- The only time-related factor (i.e. it works for a day then stops) as I see it, is the expiry of the certificate you are adding.

At this point I'm quite convinced that it's an environmental issue on your side, not a problem with the actual application.

I'm happy to assist you further, but I don't know if I can help you without more details I'm afraid.

**Comment by tsukiazuma** [comment]
I actually added the proxy's CA certificate to bytesafe. Maybe I will check it again

Thank you for your advice.

**Comment by tsukiazuma** [comment]
After check and replace CA certificate. It work.
Thank you.
