### ISSUE TITLE
Failed to find package was cached in the local repository

### ISSUE THREAD

**Issue by wonhee0410** [bitfront-se/bytesafe-ce#9]
Dear all,

Sometimes I have a problem when building a maven project with Bytesafe. How can I fix this ?

Upstreams: https://repo1.maven.org/maven2/

Bellow is the log:

`[ERROR] Failed to execute goal on project appraisal-by-video-call: Could not resolve dependencies for project xxx:video-call:jar:0.0.1: Failure to find e-iceblue:spire.doc.free:jar:5.2.0 in https://bytesafe.xxx/maven/maven-external/ was cached in the local repository, resolution will not be reattempted until the update interval of maven-external has elapsed or updates are forced -> [Help 1]`

**Comment by niclas-g** [comment]
Hi @wonhee0410 and thanks for using Bytesafe. 
We'll need some more information to be able to assist you. Do you have logs from bytesafe-ce?  The above is from maven I assume? It would be helpful to have the actual logs from bytesafe.
